# Lab4 Pytorch

In [1]:
import numpy as np
import torch

In [2]:
array = [[1,2,3],[4,5,6]]  #初始化数据

In [3]:
np_array = np.array(array)
print("Numpy Array Type: {}".format(type(np_array)))
print("Numpy Array Shape:{}".format(np_array.shape))
print(np_array)

Numpy Array Type: <class 'numpy.ndarray'>
Numpy Array Shape:(2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
tensor = torch.Tensor(array)

In [5]:
print("PyTorch Array Type:",tensor.type)
print("PyTorch Array Shape:",tensor.shape)
print(tensor)

PyTorch Array Type: <built-in method type of Tensor object at 0x7fe5686c7810>
PyTorch Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


&emsp;&emsp;这是因为PyTorch张量默认是<u>浮点型</u>的。
因此，如果您输入整数列表，则将它们转换为浮点数，
并在数字后面添加一个小数点以表示其为浮点数。

## 初始化tensor矩阵

In [6]:
np_ones = np.ones((2,3)) #生成2x3的全1矩阵
print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
torch_ones = torch.ones((2,3))
print(torch_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
print(torch.arange(10))
print(torch.rand(3,4))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0.7146, 0.6145, 0.4669, 0.9999],
        [0.7736, 0.6972, 0.4180, 0.9018],
        [0.8098, 0.6167, 0.6495, 0.3771]])


## Numpy和PyTorch之间的转换

In [18]:
np_array = np.random.rand(2,3)
print(np_array)
print(type(np_array))

[[0.86709621 0.73515508 0.92098673]
 [0.48411082 0.72018222 0.51336486]]
<class 'numpy.ndarray'>


In [20]:
# 从numpy转换为tensor
tensor1 = torch.from_numpy(np_array)
print(tensor_from_np_array)

tensor([[0.8671, 0.7352, 0.9210],
        [0.4841, 0.7202, 0.5134]], dtype=torch.float64)


In [23]:
# 从tensor转换为numpy
numpy1 = tensor1.numpy()
print(numpy1)
"""
np.allclose() 函数是用于比较两个numpy数组是否在指定的公差范围内（默认为1e-9）元素相等。
如果所有元素都相等，则返回 True，否则返回 False。
"""
print(np.allclose(np_array,numpy1))

[[0.86709621 0.73515508 0.92098673]
 [0.48411082 0.72018222 0.51336486]]
True


 ## Tensors的基本运算

In [3]:
a = torch.rand(3,4)
b = torch.ones(3,4)
print(a)
print(b)

tensor([[0.5765, 0.8880, 0.5418, 0.5061],
        [0.7357, 0.0117, 0.1354, 0.9330],
        [0.0511, 0.2714, 0.3489, 0.0291]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
print(a.reshape(2,6))  #重组成2*6的矩阵
print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(a @ b.T)
print((b.T @ a).mean())  #求均值
print((b.T @ a).std())   #求标准差
print(a.mean())
print(a.mean().item())  #将tensor转换为标量
print(type(a.mean().item()))

tensor([[0.5765, 0.8880, 0.5418, 0.5061, 0.7357, 0.0117],
        [0.1354, 0.9330, 0.0511, 0.2714, 0.3489, 0.0291]])
tensor([[1.5765, 1.8880, 1.5418, 1.5061],
        [1.7357, 1.0117, 1.1354, 1.9330],
        [1.0511, 1.2714, 1.3489, 1.0291]])
tensor([[-0.4235, -0.1120, -0.4582, -0.4939],
        [-0.2643, -0.9883, -0.8646, -0.0670],
        [-0.9489, -0.7286, -0.6511, -0.9709]])
tensor([[0.5765, 0.8880, 0.5418, 0.5061],
        [0.7357, 0.0117, 0.1354, 0.9330],
        [0.0511, 0.2714, 0.3489, 0.0291]])
tensor([[ 1.7345,  1.1262,  1.8459,  1.9758],
        [ 1.3593, 85.4507,  7.3873,  1.0718],
        [19.5545,  3.6843,  2.8662, 34.3996]])
tensor([[2.5124, 2.5124, 2.5124],
        [1.8157, 1.8157, 1.8157],
        [0.7005, 0.7005, 0.7005]])
tensor(1.2572)
tensor(0.1764)
tensor(0.4191)
0.4190537929534912
<class 'float'>


# 利用GPU进行加速计算

In [2]:
%%timeit
a = torch.rand(100,100000)
b = torch.rand(100000,1000)
c = a @ b

905 ms ± 7.23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
if torch.cuda.is_available():
    a = torch.rand(1000,100000).cuda()
    b = torch.rand().cuda()