# Lab 4
This lab introduces you to PyTorch, a popular machine learning framework. The first section compares Numpy and PyTorch for various common tasks. Then we show you a linear regression example using PyTorch. Please follow the code cell by cell and make sure that you understand how the output is generated.

The final task is to repeat the Wine categorisation task that you were introduced to in Lab 3, but this time use the PyTorch framework. We have provided the structure for a solution but you need to complete the missing sections of code. After you get this running, if you are interested, try changing the model to see how it effects the performance.

# From Numpy to PyTorch

In [ ]:
# NOTE: Only uncomment and execute the two lines below if pytorch is not installed on your PC
# This should not be needed on a lab PC
#
# import sys
# !{sys.executable} -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

In [2]:
import numpy as np    # import numpy
import torch          # import torch

In [ ]:
print(2)

: 

In [ ]:
array = [[1, 2, 3], [4, 5, 6]]  # initial data

: 

In [ ]:
np_array = np.array(array)
print("Numpy Array Type: {}".format(type(np_array)))
print("Numpy Array Shape: {}".format(np_array.shape))
print("Numpy Array:")
print(np_array)

: 

In [6]:
tensor = torch.Tensor(array)
print("PyTorch Array Type: {}".format(tensor.type))
print("PyTorch Array Shape: {}".format(tensor.shape))
print("PyTorch Array:")
print(tensor)

PyTorch Array Type: <built-in method type of Tensor object at 0x00000201716FE6D8>
PyTorch Array Shape: torch.Size([2, 3])
PyTorch Array:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Initialize Matrix (Tensor)

In [7]:
np_ones = np.ones((2,3))
print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
torch_ones = torch.ones((2,3))
print(torch_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
print(torch.arange(10))   # equivalent to np.arange
print(torch.rand(3, 4))   # euivalent to np.random.rand

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0.4615, 0.2400, 0.5899, 0.1568],
        [0.8450, 0.7637, 0.3283, 0.6452],
        [0.5417, 0.3307, 0.8219, 0.2905]])


# Conversion between Numpy and PyTorch

In [10]:
np_array = np.random.rand(2, 3)
print(np_array)
print(type(np_array))

[[0.93156572 0.09812562 0.86056975]
 [0.43252409 0.98658796 0.34303132]]
<class 'numpy.ndarray'>


In [11]:
tensor_from_np_array = torch.from_numpy(np_array)   # From numpy to pytorch
print(tensor_from_np_array)
print(tensor_from_np_array.type)

tensor([[0.9316, 0.0981, 0.8606],
        [0.4325, 0.9866, 0.3430]], dtype=torch.float64)
<built-in method type of Tensor object at 0x00000201716FE908>


In [12]:
np_array_from_tensor = tensor_from_np_array.numpy()
print(np_array_from_tensor)
print(type(np_array_from_tensor))
print(np.allclose(np_array, np_array_from_tensor))

[[0.93156572 0.09812562 0.86056975]
 [0.43252409 0.98658796 0.34303132]]
<class 'numpy.ndarray'>
True


# Basic Operations on Tensors

In [13]:
a = torch.rand(3, 4)
b = torch.ones(3, 4)

In [14]:
print(a)
print(b)

tensor([[0.5424, 0.5892, 0.3387, 0.4635],
        [0.7158, 0.0221, 0.4336, 0.7226],
        [0.3861, 0.9721, 0.9824, 0.1346]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
print(a.reshape(2, 6))  # Reshape
print(a + b)            # Addition
print(a - b)            # Subtraction
print(a * b)            # Element-wise multiplication
print(b / a)            # Element-wise division
print(a @ b.T)          # Matrix multiplication
print((b.T @ a).mean()) # Mean
print((b.T @ a).std())  # Standard deviation

tensor([[0.5424, 0.5892, 0.3387, 0.4635, 0.7158, 0.0221],
        [0.4336, 0.7226, 0.3861, 0.9721, 0.9824, 0.1346]])
tensor([[1.5424, 1.5892, 1.3387, 1.4635],
        [1.7158, 1.0221, 1.4336, 1.7226],
        [1.3861, 1.9721, 1.9824, 1.1346]])
tensor([[-0.4576, -0.4108, -0.6613, -0.5365],
        [-0.2842, -0.9779, -0.5664, -0.2774],
        [-0.6139, -0.0279, -0.0176, -0.8654]])
tensor([[0.5424, 0.5892, 0.3387, 0.4635],
        [0.7158, 0.0221, 0.4336, 0.7226],
        [0.3861, 0.9721, 0.9824, 0.1346]])
tensor([[ 1.8438,  1.6974,  2.9524,  2.1575],
        [ 1.3971, 45.1618,  2.3061,  1.3840],
        [ 2.5899,  1.0287,  1.0179,  7.4267]])
tensor([[1.9337, 1.9337, 1.9337],
        [1.8941, 1.8941, 1.8941],
        [2.4753, 2.4753, 2.4753]])
tensor(1.5758)
tensor(0.1648)


In [16]:
print(a.mean())
print(a.mean().item())          # Trick: convert 0-d tensor into scalar
print(type(a.mean().item()))

tensor(0.5253)
0.5252618193626404
<class 'float'>


# Move to GPU for Accelerated Computation

Enabling and testing the GPU: In Google Colab, to enable GPUs for the notebook, Navigate to Edit→Notebook Settings and select GPU from the Hardware Accelerator drop-down. May not be available locally on all machines using Jupyter.

In [7]:
%%timeit
a = torch.rand(1000, 100000)
b = torch.rand(100000, 1000)
c = a @ b

2.02 s ± 28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%timeit
if torch.cuda.is_available():
    
    a = torch.rand(1000, 100000).cuda()
    b = torch.rand(100000, 1000).cuda()
    c = a @ b
else:
    print("GPU acceleration not available, sorry!")

1.76 s ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
cpu_tensor = torch.rand(5)
print(cpu_tensor)
if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.cuda()
    print(gpu_tensor)
else:
    print("GPU acceleration not available, sorry!")

In [ ]:
# Let's check what GPUs we got
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("GPU acceleration not available, sorry!")

# Automatic Differentiation

In [ ]:
x = torch.tensor([1., 2., 3, 4], requires_grad=True)
y = torch.tensor([4., 5., 6, 7], requires_grad=True)
z = 5 * x + 2 * y
m = z.sum() # forward 

m.backward() # calculates the gradients
print(x.grad)
print(y.grad)

In [ ]:
x = torch.tensor([1., 2., 3], requires_grad=True)
print(x)

In [ ]:
y = torch.tensor([4., 5., 6], requires_grad=True)
z = 5 * x + 2 * y
print(z)

One advantage of using deep learning framework is that if can *automatically* calculate the gradients, which allows you to not have to write the back propagation gradients yourself. The trick is the `requires_grad`.

`requires_grad` is set to `False` by default so the Tensor is essentially similar with a `np.ndarray`. However, when explicitly set the flag to `True`, it will start to track the history of each Tensor, i.e. remember how it is created. 

In [ ]:
m = z.sum()
print(z)

In [ ]:
m.backward()
print(x.grad)
print(y.grad)

What happened?

Recall how we calculate $z_i$: $z_i = 5x_i + 2y_i, i = 0, 1, 2$.
Also, $s = \sum{z} = z_0 + z_1 + z_2$.

How to calculate $\frac{\partial{s}}{\partial{x}}$?
By chain rule, we have $\frac{\partial{s}}{\partial{x}} = \frac{\partial{s}}{\partial{z}} \cdot \frac{\partial{z}}{\partial{x}}$, therefore $\frac{\partial{s}}{\partial{x_0}} = \frac{\partial{s}}{\partial{z_0}} \cdot \frac{\partial{z_0}}{\partial{x_0}} = 1 \times 5 = 5$

Similarly $\frac{\partial{z_0}}{\partial{y_0}} = 1 \times 2 = 2$.

In short, by tracking the history of how individual variable is obtained, the program can automatically traceback and use chain rules to calculate the gradients for us, which is very helpful for training the models.

In [ ]:
m = torch.sum(x * (y ** 2) - 4 * x * y)
print(x)
print(y)
print(m)      # So you can write arbitrarily complicated expression!

In [ ]:
x.grad.zero_()   # Gradients will be accumulated, so we need to clear out first.
y.grad.zero_()

m.backward()
print(x.grad)
print(y.grad)

You can verify the results with the following derivative equations:

$\frac{\partial{m}}{\partial{x}} = (y^2 - 4y)$

$\frac{\partial{m}}{\partial{y}} = (2 xy - 4x)$

# Linear Regression

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
from tqdm import notebook
import time

plt.style.use('ggplot')

Let's first simulate some data and have a loop. 

Here for easier visualization, our feature contains only 1 variable so it can be easily shown on a 2-d figure. But the same will apply to higher dimensional data.

In [ ]:
w, b = 12, -4 # y = w * x + b

data = torch.rand(200, 1)
label = w * data + b + 0.5 * torch.randn(200, 1)

In [ ]:
plt.scatter(data, label)
plt.xlabel("x")
plt.ylabel("y")
plt.show()

In [ ]:
weight = torch.rand(1, requires_grad=True)   # Assuming y = x * w + b
bias = torch.rand(1, requires_grad=True)

In [ ]:
print(weight, bias)

In [ ]:
# Hyperparameter
learning_rate = 0.1

In [ ]:
total_steps = notebook.tqdm(range(10000))

for step in total_steps:
  prediction = weight * data + bias # forward pass 
  loss = ((prediction - label) ** 2).mean()   # Mean squared error
  if (step + 1) % 100 == 0:
    total_steps.set_description("Loss: %.4f" % loss.detach().item())

  loss.backward()
  # plt.plot(x, weight * x + bias)

  with torch.no_grad():   # Stops tracking variable
    weight -= learning_rate * weight.grad # w_new = w_old - lt*grad
    bias -= learning_rate * bias.grad
    weight.grad.zero_()   # Avoid gradients being accumulated
    bias.grad.zero_()

In [ ]:
w_hat = weight.detach().item()    # Stops tracking variable
b_hat = bias.detach().item()

print("Learned weight=%.4f, bias=%.4f" % (w_hat, b_hat))

In [ ]:
xs = np.linspace(0, 1, 100)
ys = w_hat * xs + b_hat

plt.scatter(data, label)
plt.plot(xs, ys, 'b-')
plt.xlabel("x")
plt.ylabel("y")
plt.show()

# Build a Model - Linear Regression

But it's still cumbersome to update the weights by hand! You may say.

That makes sense, so PyTorch provides a better approach to do that.

In [ ]:
import torch.nn as nn

class ManualLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()

    self.weight = nn.Parameter(torch.randn(1, requires_grad=True))
    self.bias = nn.Parameter(torch.randn(1, requires_grad=True))
    
  def forward(self, x):  
    return self.weight * x + self.bias

That's it! You only need to define how the forward pass should be calculated.

PyTorch also has some off-the-shelf loss functions and optimizers to further simplify the process.

In [ ]:
# Reset the Data

w, b = 12, -4
data = torch.rand(200, 1)
label = w * data + b + 0.5 * torch.randn(200, 1)

# Set some hyperparameters
learning_rate = 0.01

# Build a Model
model = ManualLinearRegression()
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

total_steps = notebook.tqdm(range(10000))

for step in total_steps:
  prediction = model(data)
  loss = loss_fn(label, prediction)
  if (step + 1) % 100 == 0:
    total_steps.set_description("Loss: %.4f" % loss.detach().item())
  
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

In [ ]:
for name, param in model.named_parameters():
  print("%s=%.4f" % (name, param.item()))

In fact, the *Linear Regression* is built-in module in PyTorch, so our model is just a simplified version of `nn.Linear`. You can find more built-in modules in the documentation.

# Task:
Use the Wine quality dataset (from Lab 3) to train and validate a 2-layer neural network model with ReLU non-linearity. Use nn.Linear to define fully connected layers. Complete the missing parts in code below. 



In [ ]:
# This code was written by V. Sharmanska. All rights reserved.
# Modified by Nick Hay 2023

import urllib.request
import pandas as pd

# Set the maximum precision used for printing datasets
pd.set_option('display.precision', 3)

# Copy the data to a local file
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
filename = "winequality-red.csv"
urllib.request.urlretrieve(url, filename)

# Load the CSV data into a pandas dataframe (for easy display and manipulation)
data = pd.read_csv("winequality-red.csv", sep=";")
# print(data)  # The bad way to print a dataframe
display(data)  # The good way to print a dataframe

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
from numpy.random import randn
from sklearn.preprocessing import StandardScaler
import pdb

# Create a numpy array of sample data, with labels ("quality") removed
Data = data.drop("quality", axis=1).to_numpy()
# Create a numpy array of labels
Labels = np.reshape(data["quality"].to_numpy(), (-1, 1))
# Count the number of features (the dimensionality of feature space)
num_features = Data.shape[1]

# Split the samples and labels into training and test data
X_train, X_test = np.array_split(Data, 2)
y_train, y_test = np.array_split(Labels, 2)

# Normalize the data using the mean and variance computed from the training set
# See https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
feature_scaler = StandardScaler()
X_train = feature_scaler.fit_transform(X_train)  # Note use of fit_transform() here...
X_test = feature_scaler.transform(X_test)  # and transform() here

# Augment the data to include a dimension for bias
# NOTE: Done AFTER normalisation or will be normalised to zero
X_train = np.c_[X_train, np.ones((X_train.shape[0],1))]
X_test = np.c_[X_test, np.ones((X_test.shape[0],1))]

# Display some information about our data
print(f"We have:")
print(f"{num_features} dimensions in feature space (plus bias)")
print(f"{X_train.shape[0]} training samples")
print(f"{X_test.shape[0]} test samples")
# print(X_train)  # Printing numpy arrays is not as nice as printing dataframes
display("Training data", pd.DataFrame(X_train))  # So we can do this!

Write a forward pass

In [ ]:
# Define a 2-layer MLP model
class MultilayerPerceptron(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)  # w * x + b
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, num_classes)
  
  def forward(self, x):
    #TASK: write a forward pass
    return out

Define the loss criterion as mean squared error (MSE) using `nn.MSELoss`:

In [ ]:
# Set the Data
data=torch.tensor(X_train.copy()).float()
label=torch.tensor(y_train.copy()).float()

# Set some hyperparameters
learning_rate = 0.01

# Build a Model
model = MultilayerPerceptron(12, 30, 1)
print(model)

#TASK: define loss criterion
#loss_criterion = 
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

total_steps = notebook.tqdm(range(10000))

model.train()
for step in total_steps:
  prediction = model(data)
  loss = loss_criterion(label, prediction)
  if (step + 1) % 100 == 0:
    total_steps.set_description("Loss: %.4f" % loss.detach().item())
  
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

Complete model evaluation on the test data, i.e. perform a forward pass using test data, and compute MSE.

In [ ]:
#testing
#Use test data to evaluate performace:
data=torch.tensor(X_test.copy()).float()
label=torch.tensor(y_test.copy()).float()
#TASK: compute MSE loss on the test data