In [16]:
import torch

In [17]:
# 构造一个默认Float型的张量
tensor_1 = torch.tensor((3,3))
print(tensor_1)

tensor([3, 3])


In [18]:
# 构造一个无初始化定义的张量
tensor_2  = torch.empty((3,3))
print(tensor_2)

tensor([[1.5766e-19, 1.0256e-08, 4.1019e-08],
        [3.1643e+12, 1.7340e-07, 1.7283e-04],
        [2.7001e-06, 1.2680e+16, 2.1707e-18]])


In [19]:
# 构造一个随机初始化的矩阵
tensor_3 = torch.rand((3,3))
print(tensor_3)

tensor([[0.0669, 0.4096, 0.7208],
        [0.1035, 0.0724, 0.7507],
        [0.7753, 0.4245, 0.6506]])


torch.rand和torch.randn的区别：
1、torch.rand函数生成的张量中的元素来自于均匀分布，范围在[0,1)之间，因此生成的张量中的所有元素都在[0,1)之间，不包含负值。
2、torch.randn函数生成的张量中的元素来自于标准正态分布，这意味着这些元素具有从负无穷到正无穷的可能性，因此生成的张量中可能会包含负值。

In [20]:
# 构造一个0元素矩阵
tensor_4 = torch.zeros((3,3))
print(tensor_4)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# 构造一个1元素矩阵
tensor_5 = torch.ones((3,3))
print(tensor_5)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [22]:
import numpy as np

In [23]:
# tensor转numpy
t1 = torch.rand((3,3))
t1_numpy = t1.numpy()
print(t1_numpy)

[[0.9039909  0.42705554 0.5664337 ]
 [0.4289682  0.5397436  0.75174683]
 [0.65817434 0.65714085 0.93757653]]


In [69]:
# numpy转tensor
t2_numpy = np.array([[1,2,3],[4,5,6],[7,8,9]])
t2_torch = torch.from_numpy(t2_numpy)
print(t2_torch)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [70]:
# 查看形状
t2_torch.shape

torch.Size([3, 3])

In [76]:
# 张量重构
t2_torch.resize_(1,3)
print(t2_torch)
t2_reshape = torch.reshape(t2_torch,(3,1))
print(t2_reshape)
print(t2_reshape.shape)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


torch1.resize_可以改变torch1的大小；
torch2.reshape 不会改变torch1的大小只是重构。

In [51]:
# 拉伸成一维张量
t2_torch = t2_torch.view(-1)
print(t2_torch)
print(t2_torch.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [49]:
# 增添维度
t2_unsq = torch.unsqueeze(t2_torch,dim=0)
print(t2_unsq.shape)

# 删减维度
t2_sq = torch.squeeze(t2_unsq,dim=0)
print(t2_sq.shape)

torch.Size([1, 9])
torch.Size([9])


In [84]:
# 将两个维度间的元素进行拉伸
# flatten:张量（c,w,h）,start_dim=0,end_dim=1 -->(cw,h)
t1 = torch.rand(2,3,4)
print(t1)
print(t1.shape)
print("--------从第1维开始压缩--------")
t1_flatten = torch.flatten(t1,start_dim=1)
print(t1_flatten)
print(t1_flatten.shape) 
print("---------压缩第0维和第1维-------")
t1_flatten2 = torch.flatten(t1,start_dim=0,end_dim=1)
print(t1_flatten2)
print(t1_flatten2.shape)

tensor([[[0.3102, 0.3601, 0.0646, 0.5681],
         [0.9583, 0.1583, 0.3125, 0.3873],
         [0.4327, 0.8533, 0.8343, 0.1869]],

        [[0.5178, 0.7171, 0.4725, 0.8342],
         [0.1557, 0.9474, 0.8580, 0.6445],
         [0.8351, 0.4904, 0.0109, 0.6413]]])
torch.Size([2, 3, 4])
--------从第1维开始压缩--------
tensor([[0.3102, 0.3601, 0.0646, 0.5681, 0.9583, 0.1583, 0.3125, 0.3873, 0.4327,
         0.8533, 0.8343, 0.1869],
        [0.5178, 0.7171, 0.4725, 0.8342, 0.1557, 0.9474, 0.8580, 0.6445, 0.8351,
         0.4904, 0.0109, 0.6413]])
torch.Size([2, 12])
---------压缩第0维和第1维-------
tensor([[0.3102, 0.3601, 0.0646, 0.5681],
        [0.9583, 0.1583, 0.3125, 0.3873],
        [0.4327, 0.8533, 0.8343, 0.1869],
        [0.5178, 0.7171, 0.4725, 0.8342],
        [0.1557, 0.9474, 0.8580, 0.6445],
        [0.8351, 0.4904, 0.0109, 0.6413]])
torch.Size([6, 4])


#### 拼接和拆分：  
在神经网络的前向传播过程中，往往需要对多个分支的张量加以融合或拆分

In [99]:
t3 = torch.randn(1,3,256,256) #构建维度为[1,3,256,256]、元素随机的tensor3
t4 = torch.randn(1,3,256,256)

# 在dim维度上融合
t_cat = torch.cat((t3,t4),dim=2)      #CV中常用
#t_stack = torch.stack((t3,t4),dim=2) #NLP中常用，会保留原有的tensor序列
print(t_cat.shape) 

# 拆分
# chunk:
t_chunk = torch.chunk(t_cat,chunks=3,dim=1)
print(t_chunk[1].shape)

torch.Size([1, 3, 512, 256])
torch.Size([1, 1, 512, 256])


`torch.chunk(input, chunks, dim=0)`  
input：需要被分块的张量。  
chunks：要分成的块数。  
dim：指定分块的维度，默认为 0。

### 基本运算方法

In [104]:
a = torch.ones(1,2)
b = torch.ones(1,2)
c = torch.ones(2,2)
# 基本运算方法
add = a + b
sub = a - b
div = a / b
mul = a * c  # 也可以用@或用torch.matmul(a,c)
max = c.max()
min = c.min()

# 转置
a_T = a.T

# 把数组展平为一维数组
a_ravel = a.ravel()

### 实现简单的反向传播


In [108]:
import torch

x = torch.Tensor([2])
# 初始化权重参数W，偏移量为b,并设置requires_grad=True，为自动求导
w = torch.randn(1,requires_grad=True)
b = torch.randn(1,requires_grad=True)
z = w*x + b
z.backward()  # 标量进行反向传播，向量则需要构造梯度矩阵


### 常用接口
<img src="/mnt/mydisk2/myPytorch/pic/PyTorch API汇总.png" alt="FAO" width="790">


In [4]:
import numpy as np

vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

dot_product = np.dot(vector1,vector2)

vector_length_1 = np.linalg.norm(vector1)
vector_length_2 = np.linalg.norm(vector2)

print(vector_length_1)

cosine_similarity = dot_product / (vector_length_1 * vector_length_2)

print(cosine_similarity)

3.7416573867739413
0.9746318461970762
